<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="google" content="notranslate" />
    <link rel="stylesheet" href="assets/css/style.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <title>Mogo</title>
</head>
<body>

<!--Header-->
<header class="header">
    <div class="container">
        <div class="header__inner">
            <div class="header__logo">MoGo</div>

            <nav class="nav">
                <a class="nav__link" href="#">About</a>
                <a class="nav__link"href="#">Service</a>
                <a class="nav__link"href="#">Work</a>
                <a class="nav__link"href="#">Block</a>
                <a class="nav__link"href="#">Blog</a>
                <a class="nav__link"href="#">Contact</a>
            </nav>
        </div> <!--/.header__inner-->
    </div> <!--/.container-->
</header>

<!--Intro-->
<div class="intro">
    <div class="container">
       <div class="intro__inner">
           <h2 class="intro__suptitle">Creative Template</h2>
           <h1 class="intro__title">Welcome to MoGo</h1>
           <a class="btn" href="#">Learn More</a>
        </div>
    </div>
</div>

<!--Section-->
<section class="section">
    <div class="container">

        <div class="section__header">
            <h3 class="section__suptitle" >What we doo</h3>
            <h2 class="section__title">Story about us</h2>
            <div class="section__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p></div>
        </div>

        <div class="card">
            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/about/1.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
            </div>

            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/about/2.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
            </div>

            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/about/3.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
            </div>

        </div> <!--/.card-->
    </div> <!--/.container-->
</section>

<div class="statistics">
    <div class="container">

        <div class="stat">
            <div class="stat__item">
               <div class="stat__count">42</div>
               <div class="stat__text">Web design projects</div>
           </div>
            <div class="stat__item">
                <div class="stat__count">123</div>
               <div class="stat__text">Happy client</div>
            </div>
            <div class="stat__item">
                <div class="stat__count">15</div>
               <div class="stat__text">Award winner</div>
            </div>
            <div class="stat__item">
                <div class="stat__count">99</div>
               <div class="stat__text">Cup of coffee</div>
            </div>
            <div class="stat__item">
                <div class="stat__count">24</div>
               <div class="stat__text">Members</div>
            </div>
        </div>


    </div>
</div>


<section class="section">
    <div class="container">
        <div class="section__header">
            <h3 class="section__suptitle" >Wee work with</h3>
            <h2 class="section__title">Amazing services</h2>
        </div>

        <div class="services">
            <div class="services__item">
                <img class="services__icon" src="assets/images/services/service-1.png" alt="">
                <div class="services__title">Photografy</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>

            <div class="services__item">
                 <img class="services__icon" src="assets/images/services/service-2.png" alt="">
                <div class="services__title">Web design</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>
            <div class="services__item">
                 <img class="services__icon" src="assets/images/services/service-3.png" alt="">
                <div class="services__title">Creativity</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>
        </div>

        <hr>

        <div class="services">
            <div class="services__item">
                <img class="services__icon" src="assets/images/services/service-4.png" alt="">
                <div class="services__title">Seo</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>

            <div class="services__item">
                 <img class="services__icon" src="assets/images/services/service-5.png" alt="">
                <div class="services__title">Css/Html</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>
            <div class="services__item">
                 <img class="services__icon" src="assets/images/services/service-6.png" alt="">
                <div class="services__title">Digital</div>
                <div class="services__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</div>
            </div>
        </div>

    </div> <!--/.container-->
</section>


<div class="section section--devices">
   <div class="container">

        <div class="section__header">
            <h3 class="section__suptitle" >For all devices</h3>
            <h2 class="section__title">Unique design</h2>
        </div>

       <div class="devices">
            <img class="devices__item "src="assets/images/devices/ipad.png" alt="">
            <img class="devices__item devices__item--iphone" src="assets/images/devices/iphone.png" alt="">
       </div>
   </div><!--/.container-->
</div>

<section class="section">
    <div class="container">

        <div class="section__header">
            <h3 class="section__suptitle" >Service</h3>
            <h2 class="section__title">What wee doo</h2>
             <div class="section__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
             </div>
        </div>

        <div class="wedoo">
           <div class="wedoo__item">
               <img src="assets/images/wedoo/wedoo.jpg" alt="">
           </div>
           <div class="wedoo__item">
               <div class="accordion">
                   <div class="accordion__item">
                       <div class="accordion__header">
                          <img class="accordion__icon" src="assets/images/wedoo/icon%201.png" alt="">
                           <div class="accordion__title">Photography</div>
                       </div>
                       <div class="accordion__content">
                           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                       </div>
                   </div>

                    <div class="accordion__item active">
                       <div class="accordion__header">
                          <img class="accordion__icon" src="assets/images/wedoo/icon%202.png" alt="">
                           <div class="accordion__title">Creativity</div>
                       </div>
                       <div class="accordion__content">
                           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                       </div>
                   </div>

                    <div class="accordion__item">
                       <div class="accordion__header">
                          <img class="accordion__icon" src="assets/images/wedoo/icon%203.png" alt="">
                           <div class="accordion__title">Web design</div>
                       </div>
                       <div class="accordion__content">
                           <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                       </div>
                   </div>

               </div><!--/.accordion__-->
           </div><!--/.wedoo__item-->
        </div><!--/.wedoo-->
    </div><!--/.container-->
</section>


<div class="section section--gray">
    <div class="container">

        <div class="reviews">

           <a class="reviews__btn reviews__btn--prev" href="#">Prev</a>
           <a class="reviews__btn reviews__btn--next" href="#">Next</a>

            <div class="reviews__item">
                <img class="reviews__photo" src="http://placehold.it/145" alt="">
                <div class="reviews__text">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."</div>
                <div class="reviews__autor">Jon Doe</div>
            </div>

        </div><!--/.reviews-->

    </div><!--/.container-->
</div>


<section class="section">
    <div class="container">

        <div class="section__header">
            <h3 class="section__suptitle" >Who we are</h3>
            <h2 class="section__title">Meet our team</h2>
             <div class="section__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
             </div>
        </div>

        <div class="card">
            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/team/1.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
                <div class="card__info" >
                    <div class="card__name">Matthew Dix</div>
                    <div class="card__prof">Graphic Design</div>
                </div>
            </div>

            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/team/2.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
                 <div class="card__info" >
                    <div class="card__name">Christopher Campbell</div>
                    <div class="card__prof">Branding/UX design</div>
                </div>
            </div>

            <div class="card__item">
               <div class="card__inner">
                    <div class="card__img">
                        <img src="assets/images/team/3.jpg" alt="">
                    </div>
                    <div class="card__text">Super team</div>
                </div>
                 <div class="card__info" >
                    <div class="card__name">Michael Fertig</div>
                    <div class="card__prof">Developer</div>
                </div>
            </div>

        </div><!--/.card-->
    </div><!--/.container-->
</section>

<div class="section section--gray">
    <div class="container">

        <div class="logos">
           <div class="logos__item">
               <img src="assets/images/team/logo%201.png" alt="">
           </div>

           <div class="logos__item">
               <img src="assets/images/team/logo%202.png" alt="">
           </div>

           <div class="logos__item">
               <img src="assets/images/team/logo%203.png" alt="">
           </div>

           <div class="logos__item">
               <img src="assets/images/team/logo%204.png" alt="">
           </div>

           <div class="logos__item">
               <img src="assets/images/team/logo%205.png" alt="">
           </div>

           <div class="logos__item">
               <img src="assets/images/team/logo%206.png" alt="">
           </div>
        </div>

    </div><!--/.container-->
</div>

<section class="section">
    <div class="container">
         <div class="section__header">
            <h3 class="section__suptitle" >What wee do</h3>
            <h2 class="section__title">Some of our work</h2>
             <div class="section__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
             </div>
        </div>
    </div><!--/.container-->

      <div class="works">

            <div class="works__col">
                <div class="works__item">
                    <img class="works__image" src="assets/images/works/1.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>

                <div class="works__item">
                    <img class="works__image" src="assets/images/works/2.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>
            </div>

         <div class="works__col works__col-2">
                <div class="works__item">
                    <img class="works__image" src="assets/images/works/3.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>

                <div class="works__item">
                    <img class="works__image" src="assets/images/works/4.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>
            </div>

            <div class="works__col">
                <div class="works__item">
                    <img class="works__image" src="assets/images/works/5.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>
            </div>

            <div class="works__col">
                <div class="works__item">
                    <img class="works__image" src="assets/images/works/7.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>

                <div class="works__item">
                    <img class="works__image" src="assets/images/works/8.jpg" alt="">
                    <div class="works__info">
                        <div class="works__title">Creativity Design</div>
                        <div class="works__text">Los santos form</div>
                    </div>
                </div>
            </div>
      </div><!--/.works-->

        <div class="container">

           <div class="revolt">

                <div class="reviews">
                   <a class="reviews__btn reviews__btn--prev" href="#">Prev</a>
                   <a class="reviews__btn reviews__btn--next" href="#">Next</a>
                    <div class="reviews__item">
                        <img class="reviews__photo" src="http://placehold.it/145" alt="">
                        <div class="reviews__text">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."</div>
                        <div class="reviews__autor">Jon Doe</div>
                    </div>
               </div>

           </div>
        </div>

</section>

<!--Ravsay-->
<section class="section section--ravsay">
    <div class="container">
        <div class="section__header">
            <h3 class="section__suptitle" >Happy Clients</h3>
            <h2 class="section__title">What people say</h2>
        </div>

        <div class="ravsay__items__inner">
           <div class="ravsay__colon">

            <div class="ravsay__item">
              <img clas="ravsay__img" src="assets/images/revsay/autor_1.png" alt="">
               <div class="ravsay__autor">Matthew Dix</div>
               <div class="ravsay__categorie">Graphic Design</div>
               <div class="ravsay__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p></div>
            </div>

             <div class="ravsay__item">
              <img clas="ravsay__img" src="assets/images/revsay/autor_2.png" alt="">
               <div class="ravsay__autor">Matthew Dix</div>
               <div class="ravsay__categorie">Graphic Design</div>
               <div class="ravsay__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p></div>
            </div>

           </div> <!--colon-->

             <div class="ravsay__colon">

            <div class="ravsay__item">
              <img clas="ravsay__img" src="assets/images/revsay/autor_3.png" alt="">
               <div class="ravsay__autor">Matthew Dix</div>
               <div class="ravsay__categorie">Graphic Design</div>
               <div class="ravsay__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p></div>
            </div>

             <div class="ravsay__item">
              <img clas="ravsay__img" src="assets/images/revsay/autor_4.png" alt="">
               <div class="ravsay__autor">Matthew Dix</div>
               <div class="ravsay__categorie">Graphic Design</div>
               <div class="ravsay__text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p></div>
            </div>

           </div> <!--colon-->

        </div> <!--inner-->

    </div> <!--container-->
</section>


<!--Blog-->
<section class="section section--blog">
    <div class="container">
        <div class="section__header">
            <h3 class="section__suptitle" >Our stories</h3>
            <h2 class="section__title">Latest blog</h2>
        </div>

        <div class="blog__items">
            <div class="blog__item">
                <img class="blog__img" src="assets/images/blog/article_1.jpg" alt="">
                <div class="blog__date">
                    <div class="number">15</div>
                    <div class="month">July</div>
                </div>
                <div class="blog__title">Lorem ipsum dolor sit amet</div>
                <div class="blog__text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
                <hr class="blog__line">
                <div class="blog__views">
                    <img class="im"src="assets/images/blog/view.png" alt="">
                    <div class="num">123</div>
                </div>
            </div>

            <div class="blog__item">
                <img class="blog__img" src="assets/images/blog/article_2.jpg" alt="">
                <div class="blog__date">
                    <div class="number">15</div>
                    <div class="month">July</div>
                </div>
                <div class="blog__title">Lorem ipsum dolor sit amet</div>
                <div class="blog__text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
                <hr class="blog__line">
                <div class="blog__views">
                    <img class="im"src="assets/images/blog/view.png" alt="">
                    <div class="num">123</div>
                </div>
            </div>

            <div class="blog__item">
                <img class="blog__img" src="assets/images/blog/article_3.jpg" alt="">
                <div class="blog__date">
                    <div class="number">15</div>
                    <div class="month">July</div>
                </div>
                <div class="blog__title">Lorem ipsum dolor sit amet</div>
                <div class="blog__text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
                <hr class="blog__line">
               <div class="blog__views">
                    <img class="im"src="assets/images/blog/view.png" alt="">
                    <div class="num">123</div>
                </div>
            </div>

        </div>
    </div>
</section>

<!--Map-->
<div class="map">
    <img class="map__img" src="assets/images/map/map-img.png" alt="">
    <div class="map__title">Open map</div>
</div>

<!--Footer-->
<footer class="footer">
    <div class="container">
        <div class="footer__inner">
            <div class="footer__item">
                <div class="footer__ititle">MoGo</div>
                <div class="footer__itext">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                <div class="footer__icounter">15k followers</div>

                <div class="subscribe__form">
                    <div class="subscribe__fild"></div>
                    <div class="subscribe__button"></div>
                </div>
            </div>


        </div>
    </div>
</footer>

</body>
</html>
